name: CI

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      -name: echo "Hello, World!"
        run: echo "Hello, World!"