name: CI

on:
  [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Hello, World!
        run: echo "Hello, World!"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Specify the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic python code
        run: |
          python -c "print('Hello, World!')"

  final-job:
    runs-on: ubuntu-latest
    needs: 
      - test
      - build

    steps:
      - name: Echo All Jobs Done
        run: echo "All jobs are done!"
